"""Standard training recipes for YOLO-NAS benchmarks."""

COCO_RECIPE = {
    "epochs": 100,
    "optimizer": "sgd",
    "lr": 4e-4,
    "weight_decay": 5e-4,
    "cosine_final_lr_ratio": 0.1,
    "warmup_epochs": 3,
    "ema_decay": 0.9997,
    "precision": "16-mixed",
    "input_size": 640,
    "batch_size": 32,
    "workers": 8,
    "conf_threshold": 0.001,
    "iou_threshold": 0.65,
    "augmentations": {
        "mosaic": True,
        "mosaic_prob": 1.0,
        "mixup": True,
        "mixup_prob": 0.5,
        "close_mosaic_epochs": 15,
        "hsv": True,
        "hsv_prob": 0.5,
        "channel_shuffle": True,
        "channel_shuffle_prob": 0.5,
        "flip": True,
        "flip_prob": 0.5,
        "random_crop": False,
        "affine_degrees": 0.0,
        "affine_translate": 0.25,
        "affine_scale": (0.5, 1.5),
    },
}

RF100VL_RECIPE = {
    "epochs": 75,
    "optimizer": "adamw",
    "lr": 2e-4,
    "weight_decay": 1e-5,
    "cosine_final_lr_ratio": 0.1,
    "warmup_epochs": 3,
    "ema_decay": 0.9997,
    "precision": "16-mixed",
    "input_size": 640,
    "batch_size": 16,
    "workers": 8,
    "conf_threshold": 0.001,
    "iou_threshold": 0.65,
    "augmentations": {
        "mosaic": False,
        "mixup": False,
        "close_mosaic_epochs": 0,
        "hsv": True,
        "hsv_prob": 0.5,
        "channel_shuffle": True,
        "channel_shuffle_prob": 0.5,
        "flip": True,
        "flip_prob": 0.5,
        "random_crop": False,
        "affine_degrees": 0.0,
        "affine_translate": 0.1,
        "affine_scale": (0.5, 1.5),
    },
}
